import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/utility/Navigation";
import Footer from "./components/utility/Footer";
import Script from "next/script";
// import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Support Palestine",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="google_translate_element"></div>
        <Navigation />
        <div>{children}</div>
        <Footer />
        <script
          src="//code.tidio.co/hhqgzbeuldkevhznpknxpgf5bs8y3mfy.js"
          async
        ></script>
        {/* <script id="" type="text/javascript">
         
           function googleTranslateElementInit(){
            new google.translate.TranslateElement(
               { pageLanguage: "en" },
               "google_translate_element"
               )
           }
         
        </script>
        <Script
          type="text/javascript"
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
        ></Script> */}
      </body>
    </html>
  );
}
