import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/utility/Navigation";
import Footer from "./components/utility/Footer";
// import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Support Palestine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const pathname = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
